print("              /\ ")
print("             /0 \ ")
print("            /  % \ ")
print("           /   #  \ ")
print("          / ^   *  \ ")
print("         /   *   &  \ ")
print("        /!@     ()   \ ")
print("       / &    @       \ ")
print("      /   $     %   ^  \ ")
print("     / !   () $*()  ^#  \ ")
print("    / <>(%@  *   }  :?>< \ ")
print("   /                      \ ")
print("  /                        \ ")
print(" /__________________________\ ")
print("          /         \ ")
print("         /           \ ")
print("        /_____________\ ")