print("          _      ")
print("      ___/ \___   ")
print("     /_       _\     ")
print("     _/       \_          ")
print("    /_         _\         ")
print("      \__   __/      " )
print("        /___\  ")
print("         /0\ " )
print("        /o  \ ")
print("       /  o  \ ")
print("      /  o    \ ")
print("     / .     o \ ")
print("    / o   .     \ ")
print("   /   o    .   o\ ")
print("  /  o   <    v   \ ")
print(" /> . .   v   .  . \ ")
print("/___________________\ ")
print("     /        \       ")
print("    /__________\      ")