print("                    <---------------->                       ")
print("                   /         |        \                            ")
print("                  /         _|_        \                         ")
print("                 /         |   |        \                         ")
print("                /          |   |         \                        ")
print("               |           |_ _|          |                        ")
print("               |             |            |                        ")
print("                \            |           /                        ")
print("                 \           |          /                          ")
print("                  |          |         |                        ")
print("                  |          |         |                        ")
print("                 /                      \                          ")
print("                /         /     __       \                        ")
print("               |         /_    /_/        |                     ")
print("                \       /  /  /          /                               ")
print("                 \                      /                                ")
print("                  \____________________/                                                    ")


